# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-landing-page:
    build:
      target: development
    image: fcp-fd-landing-page-development
    container_name: fcp-fd-landing-page-development
    ports:
      - "3021:3021"
      - "9021:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
