services:
  fcp-fd-landing-page:
    build:
      context: .
      target: production
    image: fcp-fd-landing-page
    container_name: fcp-fd-landing-page
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-landing-page-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
